include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # Style rules
    camel_case_types: true
    library_names: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    curly_braces_in_flow_control_structures: true
    slash_for_doc_comments: true
    # Usage rules
    prefer_interpolation_to_compose_strings: true
    prefer_collection_literals: true
    avoid_function_literals_in_foreach_calls: false
    avoid_init_to_null: true
    prefer_initializing_formals: true
    type_init_formals: true
    empty_constructor_bodies: true
    empty_statements: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_getters_setters: true
    #Design rules
    avoid_setters_without_getters: true
    avoid_return_types_on_setters: true
    parameter_assignments: true
    prefer_function_declarations_over_variables: true
    unawaited_futures: true
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    require_trailing_commas: false
    noop_primitive_operations: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/generated/intl/*
    - test/*.mocks.dart
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
    use_setters_to_change_properties: ignore
    invalid_annotation_target: ignore
